### PR TITLE
Added precompiled binaries for Win64 and Linux.

### PR DESCRIPTION
**Pull request by philipheinisch**
Would you be so kind and check if the binaries work on different systems?

### CODE REVIEW

**Comment by ranocha** [comment]
I wouldn't add binaries to the git repository. Instead, we can attach packed binaries to every release.

**Comment by philipheinisch** [comment]
After I changed the readme and created a new release with the corresponding zenodo file, I will attach the binaries to the release, but this way it was possible to test the binaries beforehand. Probably a hint in the readme pointing to https://github.com/MuMPlaCL/MatCL/releases for the latest binaries would be best?

**Comment by ranocha** [comment]
> After I changed the readme and created a new release with the corresponding zenodo file, I will attach the binaries to the release, but this way it was possible to test the binaries beforehand. Probably a hint in the readme pointing to https://github.com/MuMPlaCL/MatCL/releases for the latest binaries would be best?

This sounds very good.

**Comment by ranocha** [comment]
@philipheinisch, can you draft a new release with the binaries, please? This PR can be closed afterwards.

**Comment by ranocha** [comment]
Done in #14 and the new release.

**Pull request closed without merging**
